[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mcp-project"
version = "0.1.0"
description = "A Model Context Protocol (MCP) project"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "asyncio>=3.4.3",
    "fastmcp",
]

[project.scripts]
mcp-server = "examples.greeting.greeting_tool:main"

[project.optional-dependencies]
dev = [
    "black",
    "isort",
    "mypy",
    "pytest",
]

[tool.black]
line-length = 88
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 88

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true

[tool.hatch.build]
packages = ["src/examples"]

[tool.hatch.build.targets.wheel]
only-include = ["src"]

[tool.hatch.build.targets.sdist]
include = [
    "src",
    "README.md",
]
